# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 486)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ico/cloud_72.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #282727;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#121212;\n"
"    background-color: #3B3838;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title, 0, QtCore.Qt.AlignHCenter)
        self.label_token = QtWidgets.QLabel(self.centralwidget)
        self.label_token.setObjectName("label_token")
        self.verticalLayout.addWidget(self.label_token)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.lineEdit_token = QtWidgets.QLineEdit(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_token.sizePolicy().hasHeightForWidth())
        self.lineEdit_token.setSizePolicy(sizePolicy)
        self.lineEdit_token.setStyleSheet("border: none;\n"
"border-bottom: 1px solid white;\n"
"outline-color:  5px solid red;")
        self.lineEdit_token.setObjectName("lineEdit_token")
        self.btn_backspace = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backspace.sizePolicy().hasHeightForWidth())
        self.btn_backspace.setSizePolicy(sizePolicy)
        self.btn_backspace.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_backspace.setMaximumSize(QtCore.QSize(24, 15))
        self.btn_backspace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_backspace.setStyleSheet("QPushButton:hover {\n"
"    background-color: #951a0f;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #121212;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ico/delete_fill_white_withbacground.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_backspace.setIcon(icon1)
        self.btn_backspace.setIconSize(QtCore.QSize(25, 25))
        self.btn_backspace.setFlat(False)
        self.btn_backspace.setObjectName("btn_backspace")
        self.verticalLayout.addWidget(self.splitter)
        self.label_text_edit = QtWidgets.QLabel(self.centralwidget)
        self.label_text_edit.setObjectName("label_text_edit")
        self.verticalLayout.addWidget(self.label_text_edit, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_json = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_json.setMinimumSize(QtCore.QSize(510, 300))
        self.textEdit_json.setStyleSheet("border: 1px solid white;\n"
"")
        self.textEdit_json.setAcceptRichText(False)
        self.textEdit_json.setObjectName("textEdit_json")
        self.verticalLayout.addWidget(self.textEdit_json)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.btn_get = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get.sizePolicy().hasHeightForWidth())
        self.btn_get.setSizePolicy(sizePolicy)
        self.btn_get.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_get.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_get.setAutoFillBackground(False)
        self.btn_get.setObjectName("btn_get")
        self.btn_paste = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_paste.sizePolicy().hasHeightForWidth())
        self.btn_paste.setSizePolicy(sizePolicy)
        self.btn_paste.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_paste.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_paste.setObjectName("btn_paste")
        self.btn_save_as = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_as.sizePolicy().hasHeightForWidth())
        self.btn_save_as.setSizePolicy(sizePolicy)
        self.btn_save_as.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_save_as.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_as.setObjectName("btn_save_as")
        self.btn_clear = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_decode = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_decode.sizePolicy().hasHeightForWidth())
        self.btn_decode.setSizePolicy(sizePolicy)
        self.btn_decode.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_decode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_decode.setObjectName("btn_decode")
        self.verticalLayout.addWidget(self.splitter_2)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setStyleSheet("color: rgb(111, 111, 111)")
        self.label_version.setObjectName("label_version")
        self.verticalLayout.addWidget(self.label_version, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GNRQT"))
        self.label_title.setText(_translate("MainWindow", "Запрос к облаку Эвотор"))
        self.label_token.setText(_translate("MainWindow", "Токен приложения"))
        self.lineEdit_token.setPlaceholderText(_translate("MainWindow", "00000000-0000-0000-0000-000000000000"))
        self.btn_backspace.setToolTip(_translate("MainWindow", "Очистить поле для токена"))
        self.label_text_edit.setText(_translate("MainWindow", "Вставьте json в поле"))
        self.textEdit_json.setPlaceholderText(_translate("MainWindow", "Вставьте JSON -> {\"key\": \"value\"}"))
        self.btn_get.setToolTip(_translate("MainWindow", "Сделать запрос к облаку"))
        self.btn_get.setText(_translate("MainWindow", "Get"))
        self.btn_paste.setToolTip(_translate("MainWindow", "Вставить содержимое буфера обмена"))
        self.btn_paste.setText(_translate("MainWindow", "Paste"))
        self.btn_save_as.setToolTip(_translate("MainWindow", "Сохранить как... в файл"))
        self.btn_save_as.setText(_translate("MainWindow", "Save as"))
        self.btn_clear.setToolTip(_translate("MainWindow", "Очистить поле для текста"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_decode.setToolTip(_translate("MainWindow", "Декодировать содержимое без сохранения"))
        self.btn_decode.setText(_translate("MainWindow", "Decode"))
        self.label_version.setToolTip(_translate("MainWindow", "Версия приложения"))
        self.label_version.setText(_translate("MainWindow", "1.0.0"))
        self.statusbar.setToolTip(_translate("MainWindow", "Статус выполнения"))
